name: CI-ASan

on:
  pull_request:
  push:
    branches:
      - KEM-POP

jobs:
  asan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LLVM symbolizer
        run: sudo apt-get update && sudo apt-get install -y llvm

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Run tests with AddressSanitizer
        env:
          RUSTFLAGS: "-Z sanitizer=address"
          RUSTDOCFLAGS: "-Z sanitizer=address"
          ASAN_SYMBOLIZER_PATH: "/usr/bin/llvm-symbolizer"
          RUST_BACKTRACE: "1"
        run: cargo +nightly test -- --nocapture
